set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'hiroppy/tmux-agent-sidebar'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:UTF-8"
set -g extended-keys on
set -ga terminal-features "*:extkeys"

# window 编号从 1 开始
set -g base-index 1
setw -g pane-base-index 1

# 默认 fish shell
set-option -g default-shell /opt/homebrew/bin/fish 

# 鼠标支持
set -g mouse on

# Window tab style
set -g status-style "bg=black,fg=black" # 
set -g window-status-separator " "  
set -g window-status-format " #I:#W "
set -g window-status-style "bg=green,fg=black"
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "fg=black,bg=yellow"
set -g status-interval 1   # 状态栏刷新间隔（单位：秒）
set -g status-position bottom # 状态栏位置（top 或 bottom）
set -g status-left "#[bg=blue,fg=black]  #S #[bg=black] #[default]" # 左侧
set -g status-left-length 30  # 确保左侧区域固定长度
set -g status-left-length 100  # 确保右侧区域固定长度

# claude code
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# ---------- 快捷键 ----------------

unbind %
unbind '"'

bind-key o choose-tree -s -O time
bind-key l switch -l
# 重加载配置
bind-key r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
# 重设分屏
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
