set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'spywhere/tmux-now-playing'
set -g @now-playing-auto-interval 'yes'
set -g @now-playing-playing-icon ''
set -g @now-playing-paused-icon ''
set -g @now-playing-status-format "{icon} {scrollable} [{position}/{duration}]"

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:UTF-8"
set -g extended-keys on
set -ga terminal-features "*:extkeys"

set-option -g default-shell /opt/homebrew/bin/fish # 默认 fish shell
set -g mouse on
# Window tab style
set -g status-style "bg=default,fg=default" # 
set -g window-status-separator " "  
set -g window-status-format " #I:#W "
set -g window-status-style "bg=green,fg=black"
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "fg=black,bg=yellow"
set -g status-interval 1   # 状态栏刷新间隔（单位：秒）
set -g status-position bottom # 状态栏位置（top 或 bottom）
set -g status-right " #{now_playing} " # 右侧
set -g status-left "#[bg=blue,fg=black]  #S #[bg=black] #[default]" # 左侧
set -g status-left-length 30  # 确保左侧区域固定长度
set -g status-left-length 100  # 确保右侧区域固定长度

# claude code
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'


bind-key o choose-tree -s -O time
bind-key l switch -l

run '~/.tmux/plugins/tpm/tpm'

